deployment:
  replicas: 1

  envoyGateway:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 512Mi

# podDisruptionBudget:
#   minAvailable: 1

config:
  envoyGateway:
    logging:
      level:
        default: info

kubernetesClusterDomain: cluster.local

## NOTE: The controller is not the packet-forwarding data plane, so it doesn't need enormous resources.